//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.TripToLocations = new HashSet<TripToLocation>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StreetAddress { get; set; }
        public string CityTown { get; set; }
        public string State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public string LattitudeDirection { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public string LongitudeDirection { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<TripToLocation> TripToLocations { get; set; }
    }
}
