//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Comments = new HashSet<Comment>();
            this.LocationToTrips = new HashSet<LocationToTrip>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StreetAddress { get; set; }
        public string CityTown { get; set; }
        public string State { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public string LattitudeDirection { get; set; }
        public Nullable<double> Lattitude { get; set; }
        public string LongitudeDirection { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Shared { get; set; }
        public bool Viewed { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LocationToTrip> LocationToTrips { get; set; }
    }
}
