//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripToLocation
    {
        public int ID { get; set; }
        public int TripID { get; set; }
        public int LocationID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
