//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.TripToLocations = new HashSet<TripToLocation>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string TargetedSpecies { get; set; }
        public string WaterConditions { get; set; }
        public string WeatherConditions { get; set; }
        public string DateOfTrip { get; set; }
        public string FliesLuresUsed { get; set; }
        public string CatchOfTheDay { get; set; }
        public string OtherNotes { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<TripToLocation> TripToLocations { get; set; }
    }
}
